if (showimg)
	draw_sprite_stretched(pauseimg, 0, 0, 0, surface_get_width(application_surface) + 1, surface_get_height(application_surface))
if (!surface_exists(surf))
    surf = surface_create(surface_get_width(application_surface), surface_get_height(application_surface))
surface_set_target(surf)
draw_clear(c_black)
gpu_set_blendmode(bm_subtract)
if (!blocked)
	draw_sprite_ext(spr_fade, 0, surface_get_width(application_surface) / 2, surface_get_height(application_surface) / 2 + 30, scale, scale, angle, c_white, 1)
gpu_set_blendmode(bm_normal)
surface_reset_target()
draw_surface(surf, 0, 0)