if (!surface_exists(surf))
    surf = surface_create(surface_get_width(application_surface), surface_get_height(application_surface))
surface_set_target(surf)
draw_clear(c_black)
gpu_set_blendmode(bm_subtract)
draw_sprite_ext(spr_fade, 0, 480, 270, scale, scale, angle, c_white, 1)
gpu_set_blendmode(bm_normal)
surface_reset_target()
draw_surface(surf, camera_get_view_x(view_camera[0]), camera_get_view_y(view_camera[0]))